apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-and-mongodb
  template:
    metadata:
      labels:
        app: cart-and-mongodb
    spec:
      containers:
      - name: cart-app
        image: yukc09/ecommer:latest
        resources:
          requests:
            cpu: 50m
            memory: 128Mi 
          limits:
            cpu: 100m  
            memory: 200Mi
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: cart-app-configmap
                key: MONGODB_URI
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: cart-app-configmap
                key:  PORT     
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "shopping_cart"
--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
